In [4]:
import numpy as np


# Criando Arrays

In [5]:
import numpy as np

# A partir de uma lista
array = np.array([1, 2, 3])

# Arrays de zeros, uns ou valores aleatórios
zeros = np.zeros((2, 3))         # 2 linhas, 3 colunas
ones = np.ones((3, 3))           # 3x3 matriz de uns
rand = np.random.rand(2, 2)      # Matriz 2x2 com valores aleatórios

# Arrays com sequência de números
arange = np.arange(0, 10, 2)     # De 0 a 10 com passo de 2
linspace = np.linspace(0, 1, 5)  # 5 números igualmente espaçados entre 0 e 1


# Propriedades do Array

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)   # Dimensões (2, 3)
print(array.ndim)    # Número de dimensões (2D)
print(array.size)    # Número total de elementos (6)
print(array.dtype)   # Tipo dos elementos (int32, float64, etc.)


# Operações matematicas

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Operações elementares
print(a + b)         # Soma: [5, 7, 9]
print(a * b)         # Produto: [4, 10, 18]
print(a / 2)         # Divisão: [0.5, 1.0, 1.5]

# Funções matemáticas
print(np.sin(a))     # Seno de cada elemento
print(np.exp(a))     # Exponencial de cada elemento


[5 7 9]
[ 4 10 18]
[0.5 1.  1.5]
[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]


# Manipulação de arrays


In [7]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Indexação
print(array[0, 1])    # Elemento na linha 0, coluna 1 (2)
print(array[:, 0])    # Primeira coluna: [1, 4]

# Slicing
print(array[0, :])    # Primeira linha: [1, 2, 3]
print(array[1, 1:])   # Segunda linha, colunas 1 até o final: [5, 6]

# Transposição
print(array.T)        # Troca linhas por colunas


2
[1 4]
[1 2 3]
[5 6]
[[1 4]
 [2 5]
 [3 6]]


# Estatisticas

In [8]:
array = np.array([1, 2, 3, 4, 5])

print(np.mean(array))  # Média
print(np.median(array))  # Mediana
print(np.std(array))    # Desvio padrão
print(np.sum(array))    # Soma dos elementos
print(np.max(array))    # Máximo valor


3.0
3.0
1.4142135623730951
15
5


# Algebra linear

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Produto de matrizes
print(np.dot(A, B))

# Determinante
print(np.linalg.det(A))

# Inversa
print(np.linalg.inv(A))


# Masks